### ISSUE TITLE
Response Latency

### ISSUE THREAD

**Issue by melissacaras** [dstolz/epsych#38]
I'm using the ep_2AFC macro as part of my RPVds circuit.  I'd like to save the response latency on a trial-by-trial basis. The response latency output of the macro does not seem to be updating correctly, however. (The value just stays at zero, even though everything else in the circuit, including the response code, works perfectly).  Have others run into this issue?  If so, any suggestions on how to fix it? 

Thanks!

Melissa

**Comment by dstolz** [comment]
Not certain why the ep_2AFC macro is not properly reporting response latency.  I will look into this tomorrow, but in the mean time, you can probably use the "clock" output through a latch component that is triggered when the response code changes from zero (use the icompare component).  I think that's how response latency works (is supposed to work) in the macro.

**Comment by melissacaras** [comment]
Thanks, Dan. I was able to correctly capture the response latency (outside of the macro) by using the A or B jumpers to trigger a latch component.  When a response is made (either A or B == high), the latch captures the the value of the trial clock at that moment. If no active response was made by the animal, both A and B go high and the trial clock resets to 0, which is captured by the latch.

I suspect the error in the macro has something to do with the shift component.  I didn't try editing the macro myself, for fear of creating additional problems.

**Comment by dstolz** [comment]
Sorry, meant to get this sooner.  I did try out the ep_2AFC.rcm macro today and was able to get the correct response latency.  I'm not sure what the issue might be since I was unable to replicate it.... to be continued....
